seed: 12345
logdata_propensity:
  train_val_test_ratio:
    - 0.8
    - 0.1
    - 0.1
  density: 0.05
  exposure_bias: 0.5
  behavior_policy: "random"
tables:
  interaction:
    data_path: "./data/kuairec/small_matrix.csv"
    features:
      timestamp: "float"
  user:
    data_path: "./data/kuairec/user_features.csv"
    features:
      # feature name: data type
      onehot_feat0: "label"
      onehot_feat1: "label"
      onehot_feat2: "label"
      onehot_feat6: "label"
      onehot_feat11: "label"
      onehot_feat12: "label"
      onehot_feat13: "label"
      onehot_feat14: "label"
      register_days: "int"

  video:
    daily:
      data_path: "./data/kuairec/item_daily_features.csv"
      features:
        play_progress: "float"
        video_duration: "float"
        like_cnt: "int"
        share_user_num: "int"
    category:
      data_path: "./data/kuairec/item_categories.csv"
      features:
        feat: "multilabel"

mf:
  n_epochs: 10
  n_factors: 30
  scale: 0.05
  lr: 0.001
  reg: 0.01
  batch_size: 256

fm:
  n_epochs: 10
  n_factors: 30
  scale: 0.05
  lr: 0.001
  reg: 0.01
  batch_size: 256
